In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt

from sklearn.metrics import mean_squared_error as mse

from sklearn.linear_model import Lasso
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor

In [2]:
X_test = pd.read_csv("./Dataset/Preprocessed_Supplemental_Data.csv")
X_train = pd.read_csv("./Dataset/train_final.csv")
X_train.drop("Unnamed: 0", axis = 1, inplace=True)
X_test.head()

Count        Open        Volume  Range_Close_Open  Range_High_Low  \
0  602283.0  362.485558  1.671106e+06         -0.017399        0.973721   
1  475077.0  363.358494  1.147771e+06          0.021606        0.743932   
2  412259.0  378.132484  1.036151e+06          0.003083        0.596272   
3  585125.0  360.290954  1.792937e+06         -0.020629        0.849804   
4  342144.0  352.094678  9.547149e+05         -0.004823        0.652008   

   Asset_ID    Target  
0         0 -0.000298  
1         0  0.000393  
2         0 -0.000032  
3         0 -0.000182  
4         0 -0.000113

In [3]:
y_test = X_test['Target']
y_train = X_train['Target']
X_test.drop("Target", axis = 1, inplace=True)
X_train.drop("Target", axis = 1, inplace=True)
X_test.head()

Count        Open        Volume  Range_Close_Open  Range_High_Low  \
0  602283.0  362.485558  1.671106e+06         -0.017399        0.973721   
1  475077.0  363.358494  1.147771e+06          0.021606        0.743932   
2  412259.0  378.132484  1.036151e+06          0.003083        0.596272   
3  585125.0  360.290954  1.792937e+06         -0.020629        0.849804   
4  342144.0  352.094678  9.547149e+05         -0.004823        0.652008   

   Asset_ID  
0         0  
1         0  
2         0  
3         0  
4         0

In [4]:
model_lgbm = LGBMRegressor(n_estimators = 10000,
 learning_rate = 0.123032951985257,
 num_leaves = 2580,
 max_depth = 11,
 min_data_in_leaf = 9400,
 max_bin = 222,
 lambda_l1 = 10,
 lambda_l2 = 45,
 min_gain_to_split = 0.43596722774173646,
 reg_alpha = 0.013729311632718602,
 reg_lambda = 0.7043903261172909,
 bagging_fraction = 0.8,
 bagging_freq = 1,
 feature_fraction = 0.4)

fit = model_lgbm.fit(X_train, y_train)
preds_lgbm = fit.predict(X_test)
preds_lgbm

[LightGBM] [Warning] lambda_l1 is set=10, reg_alpha=0.013729311632718602 will be ignored. Current value: lambda_l1=10
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] min_gain_to_split is set=0.43596722774173646, min_split_gain=0.0 will be ignored. Current value: min_gain_to_split=0.43596722774173646
[LightGBM] [Warning] lambda_l2 is set=45, reg_lambda=0.7043903261172909 will be ignored. Current value: lambda_l2=45
[LightGBM] [Warning] feature_fraction is set=0.4, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4
[LightGBM] [Warning] min_data_in_leaf is set=9400, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=9400
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1


array([2.40898523e-06, 2.40898523e-06, 2.40898523e-06, ...,
       2.40898523e-06, 2.40898523e-06, 2.40898523e-06])

In [5]:
mse_lgbm = mse(y_test, preds_lgbm)
10e5*mse_lgbm

0.09780312535997492

In [6]:
model_xgb = XGBRegressor(learning_rate = 0.05562856044860366,
 max_depth = 285,
 max_leaves = 4,
 n_estimators = 807,
 reg_alpha = 0.1579588947337379,
 reg_lambda = 0.3346272402019721)

fit = model_xgb.fit(X_train, y_train)
preds_xgb = fit.predict(X_test)
preds_xgb

array([0.01443528, 0.01443528, 0.01443528, ..., 0.01360792, 0.01360792,
       0.01360792], dtype=float32)

In [7]:
mse_xgb = mse(y_test, preds_xgb)
10e5*mse_xgb

200.27929889449638

In [8]:
model_lasso = Lasso(alpha = 0.1915391)

fit = model_lasso.fit(X_train, y_train)
preds_lasso = fit.predict(X_test)
preds_lasso

/home/sameep/.local/lib/python3.8/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)


array([2.40898517e-06, 2.40898517e-06, 2.40898517e-06, ...,
       2.40898517e-06, 2.40898517e-06, 2.40898517e-06])

In [9]:
mse_lasso = mse(preds_lasso, y_test)
10e5*mse_lasso

0.09780312535995492